services:
  gateway:
    image: openresty/openresty:1.27.1.2-0-alpine-fat
    container_name: openresty-gateway-mvp
    working_dir: /etc/openresty
    command:
      - openresty
      - -g
      - daemon off;
    ports:
      - "443:8443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./conf:/etc/openresty/conf:ro
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./lib:/etc/openresty/lib:ro
      - ./logs:/var/log/openresty
      - /etc/letsencrypt:/etc/letsencrypt:ro
