services:
  gateway:
    image: openresty/openresty:1.27.1.2-0-alpine-fat
    container_name: openresty-gateway-mvp
    working_dir: /workspace
    command:
      - openresty
      - -g
      - daemon off;
      - -c
      - /workspace/conf/nginx.conf
    ports:
      - "8080:8080"
    extra_hosts:
      - "backend-test.local:host-gateway"
    volumes:
      - .:/workspace
