server {
    listen 8080;
    server_name admin-test.local;
    access_log /var/log/openresty/admin-test.local.access.log json_combined;
    error_log /var/log/openresty/admin-test.local.error.log warn;

    default_type application/json;

    location = / {
        content_by_lua_block {
            ngx.say('{"site":"admin","service":"openresty-gateway-mvp","message":"separate site config loaded from conf.d"}')
        }
    }

    location = /health {
        content_by_lua_block {
            ngx.say('{"status":"ok","site":"admin"}')
        }
    }
}
