server {
    listen 8080;
    server_name gateway-test.local;
    access_log /workspace/logs/gateway-test.local.access.log json_combined;
    error_log /workspace/logs/gateway-test.local.error.log warn;

    default_type application/json;

    location = /health {
        content_by_lua_block {
            ngx.say('{"status":"ok","service":"gateway"}')
        }
    }

    location = / {
        content_by_lua_block {
            ngx.say('{"site":"gateway","service":"openresty-gateway-mvp","endpoints":["/health","/api/demo","/api/secure-demo"]}')
        }
    }

    location = /api/demo {
        access_by_lua_block {
            require("gateway.waf").check()

            require("gateway.rate_limit").check({
                key = ngx.var.remote_addr,
                limit = 5,
                window = 60,
            })
        }

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host backend-test.local;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://192.168.1.101:9001;
    }

    location = /api/secure-demo {
        access_by_lua_block {
            require("gateway.waf").check()

            require("gateway.auth").check_jwt({
                secret = "openresty-dev-secret",
                issuer = "backend-test-auth",
                audience = "gateway-test",
            })

            require("gateway.rate_limit").check({
                key = ngx.var.remote_addr,
                limit = 5,
                window = 60,
            })
        }

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host backend-test.local;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://192.168.1.101:9001/api/demo;
    }
}
